global:
  scrape_interval: 15s # Frequency data is scraped from targets. Default is every 1 minute.

scrape_configs:
  - job_name: 'proxmox_hosts'
    static_configs:
      - targets: ['0.0.0.0:9100'] # IP de votre proxmox principal
      # - targets: ['0.0.0.0:9100'] # IP de votre second proxmox au besoin
